"""Cross-module stable models and public ports (spec v0.1)."""

from .documents import (
    BlockSpan,
    Citation,
    CoverageUnit,
    DocumentIdentity,
    EvidenceBlock,
    ExtractResult,
    Locator,
    NormalizationInput,
    NormalizedDocument,
    RetrievalHit,
)
from .errors import DomainError
from .research import (
    BudgetUsage,
    Checkpoint,
    Conflict,
    ContextFilter,
    ContextPackage,
    ContextRequest,
    CoverageAssessment,
    EvidenceItem,
    EvidenceReview,
    MaterialScope,
    ProviderReport,
    QuestionCoverage,
    ReportSection,
    ResearchDecision,
    ResearchGap,
    ResearchPlan,
    ResearchReport,
    ResearchResult,
    ResearchTask,
    SearchBatch,
    SearchDirection,
    SearchHit,
    SearchOccurrence,
    SearchQuery,
    SearchRequest,
)
from .resources import FetchRequest, FetchResult, Resource, ResourceOrigin

# Resolve the provenance -> SearchOccurrence forward reference. SearchOccurrence
# lives in research.py (which in turn imports Citation/Chunk from documents),
# so the cross-module reference is materialized here after both are loaded.
_normalization_types = {"SearchOccurrence": SearchOccurrence}
NormalizationInput.model_rebuild(_types_namespace=_normalization_types)
NormalizedDocument.model_rebuild(_types_namespace=_normalization_types)

__all__ = [
    "BlockSpan",
    "BudgetUsage",
    "Checkpoint",
    "Citation",
    "Conflict",
    "ContextFilter",
    "ContextPackage",
    "ContextRequest",
    "CoverageAssessment",
    "CoverageUnit",
    "DocumentIdentity",
    "DomainError",
    "EvidenceBlock",
    "EvidenceItem",
    "EvidenceReview",
    "ExtractResult",
    "FetchRequest",
    "FetchResult",
    "Locator",
    "MaterialScope",
    "NormalizationInput",
    "NormalizedDocument",
    "ProviderReport",
    "QuestionCoverage",
    "ReportSection",
    "ResearchDecision",
    "ResearchGap",
    "ResearchPlan",
    "ResearchReport",
    "ResearchResult",
    "ResearchTask",
    "Resource",
    "ResourceOrigin",
    "RetrievalHit",
    "SearchBatch",
    "SearchDirection",
    "SearchHit",
    "SearchOccurrence",
    "SearchQuery",
    "SearchRequest",
]
