/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FactCheckIndexRouteImport } from './routes/fact-check/index'
import { Route as FactCheckCheckIdRouteImport } from './routes/fact-check.$checkId'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as MediaIndexRouteImport } from './routes/media/index'
import { Route as MediaJobIdRouteImport } from './routes/media.$jobId'
import { Route as MonitorIndexRouteImport } from './routes/monitor/index'
import { Route as MonitorMonitorIdRouteImport } from './routes/monitor.$monitorId'
import { Route as ResearchIndexRouteImport } from './routes/research/index'
import { Route as ResearchConversationIdRouteImport } from './routes/research.$conversationId'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FactCheckIndexRoute = FactCheckIndexRouteImport.update({
  id: '/fact-check/',
  path: '/fact-check/',
  getParentRoute: () => rootRouteImport,
} as any)
const FactCheckCheckIdRoute = FactCheckCheckIdRouteImport.update({
  id: '/fact-check/$checkId',
  path: '/fact-check/$checkId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaJobIdRoute = MediaJobIdRouteImport.update({
  id: '/media/$jobId',
  path: '/media/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorIndexRoute = MonitorIndexRouteImport.update({
  id: '/monitor/',
  path: '/monitor/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorMonitorIdRoute = MonitorMonitorIdRouteImport.update({
  id: '/monitor/$monitorId',
  path: '/monitor/$monitorId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchConversationIdRoute = ResearchConversationIdRouteImport.update({
  id: '/research/$conversationId',
  path: '/research/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fact-check/$checkId': typeof FactCheckCheckIdRoute
  '/media/$jobId': typeof MediaJobIdRoute
  '/monitor/$monitorId': typeof MonitorMonitorIdRoute
  '/research/$conversationId': typeof ResearchConversationIdRoute
  '/fact-check/': typeof FactCheckIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/media/': typeof MediaIndexRoute
  '/monitor/': typeof MonitorIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fact-check/$checkId': typeof FactCheckCheckIdRoute
  '/media/$jobId': typeof MediaJobIdRoute
  '/monitor/$monitorId': typeof MonitorMonitorIdRoute
  '/research/$conversationId': typeof ResearchConversationIdRoute
  '/fact-check': typeof FactCheckIndexRoute
  '/library': typeof LibraryIndexRoute
  '/media': typeof MediaIndexRoute
  '/monitor': typeof MonitorIndexRoute
  '/research': typeof ResearchIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fact-check/$checkId': typeof FactCheckCheckIdRoute
  '/media/$jobId': typeof MediaJobIdRoute
  '/monitor/$monitorId': typeof MonitorMonitorIdRoute
  '/research/$conversationId': typeof ResearchConversationIdRoute
  '/fact-check/': typeof FactCheckIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/media/': typeof MediaIndexRoute
  '/monitor/': typeof MonitorIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fact-check/$checkId'
    | '/media/$jobId'
    | '/monitor/$monitorId'
    | '/research/$conversationId'
    | '/fact-check/'
    | '/library/'
    | '/media/'
    | '/monitor/'
    | '/research/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fact-check/$checkId'
    | '/media/$jobId'
    | '/monitor/$monitorId'
    | '/research/$conversationId'
    | '/fact-check'
    | '/library'
    | '/media'
    | '/monitor'
    | '/research'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/fact-check/$checkId'
    | '/media/$jobId'
    | '/monitor/$monitorId'
    | '/research/$conversationId'
    | '/fact-check/'
    | '/library/'
    | '/media/'
    | '/monitor/'
    | '/research/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FactCheckCheckIdRoute: typeof FactCheckCheckIdRoute
  MediaJobIdRoute: typeof MediaJobIdRoute
  MonitorMonitorIdRoute: typeof MonitorMonitorIdRoute
  ResearchConversationIdRoute: typeof ResearchConversationIdRoute
  FactCheckIndexRoute: typeof FactCheckIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  MediaIndexRoute: typeof MediaIndexRoute
  MonitorIndexRoute: typeof MonitorIndexRoute
  ResearchIndexRoute: typeof ResearchIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fact-check/': {
      id: '/fact-check/'
      path: '/fact-check'
      fullPath: '/fact-check/'
      preLoaderRoute: typeof FactCheckIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fact-check/$checkId': {
      id: '/fact-check/$checkId'
      path: '/fact-check/$checkId'
      fullPath: '/fact-check/$checkId'
      preLoaderRoute: typeof FactCheckCheckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/': {
      id: '/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$jobId': {
      id: '/media/$jobId'
      path: '/media/$jobId'
      fullPath: '/media/$jobId'
      preLoaderRoute: typeof MediaJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor/': {
      id: '/monitor/'
      path: '/monitor'
      fullPath: '/monitor/'
      preLoaderRoute: typeof MonitorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor/$monitorId': {
      id: '/monitor/$monitorId'
      path: '/monitor/$monitorId'
      fullPath: '/monitor/$monitorId'
      preLoaderRoute: typeof MonitorMonitorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/': {
      id: '/research/'
      path: '/research'
      fullPath: '/research/'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$conversationId': {
      id: '/research/$conversationId'
      path: '/research/$conversationId'
      fullPath: '/research/$conversationId'
      preLoaderRoute: typeof ResearchConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FactCheckCheckIdRoute: FactCheckCheckIdRoute,
  MediaJobIdRoute: MediaJobIdRoute,
  MonitorMonitorIdRoute: MonitorMonitorIdRoute,
  ResearchConversationIdRoute: ResearchConversationIdRoute,
  FactCheckIndexRoute: FactCheckIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  MediaIndexRoute: MediaIndexRoute,
  MonitorIndexRoute: MonitorIndexRoute,
  ResearchIndexRoute: ResearchIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
